<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="download %281%29.jpg" />
    <None Remove="How we got back on top.jpg" />
    <None Remove="moletom-vermelho_640x640+fill_ffffff.png" />
    <None Remove="Prod_6.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.4" />
    <PackageReference Include="MySql.Data" Version="9.7.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="download (1).jpg" />
    <Resource Include="How we got back on top.jpg" />
    <Resource Include="moletom-vermelho_640x640+fill_ffffff.png" />
    <Resource Include="Prod_6.jpg" />
  </ItemGroup>

</Project>
